dataset:
  name: PDE_KS
  pair_id:
  - 6
  - 7
model:
  dropout: 0.25
  horizon: 30
  kernel_dim: 32
  lag: 30
  lr: 0.001
  n_blocks: 5
  weight_decay: 0.0001
  batch_size: 5
  criterion_weights:
  - 1
  - 1
  - 1
  data_transform: mean
  decoder_config: decoder/default
  early_stopping_epochs: 60
  embedding_config: embedding/repeat
  encoder_config: encoder/default_no_skip
  loss: informer_rmse
  max_epochs: 50
  mlp_n_layers: 1
  name: spacetime
  no_wandb: true
  norm_order: 1
  output_config: output/default
  seed: 0
  train_split: 0.8
  device: cuda:1
  val_metric: informer_rmse
